version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - '5437:5432'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
