default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  host: localhost
  database: trading_app_development
  username: dev
  password: dev
  port: 5437
  <<: *default

test:
  host: localhost
  database: trading_app_test
  username: dev
  password: dev
  port: 5437
  <<: *default

production:
  <<: *default
  database: trading_app_production
  username: trading_app
  password: <%= ENV['TRADING_APP_DATABASE_PASSWORD'] %>
