meta_product_name: "Disciplined Trader"
meta_title: "Disciplined Trader - Become a Disciplined Trader"
meta_description: "Collaborate efficiently with other traders. Organise and automate your trading workflow."
meta_image: "cover.png" # should exist in `app/assets/images/
